# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'XXBScrollVIewAutoRevolve' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'XXBLibs', :git => "https://github.com/sixTiger/XXBLibs"
    pod 'XXBNav', :git => "https://github.com/sixTiger/XXBNav"
    pod 'XXBRefresh', :git => "https://github.com/sixTiger/XXBRefresh"

end
